### ISSUE TITLE
Use flownative/docker-nginx:4

### ISSUE THREAD

**Issue by kdambekalns** [flownative/localbeach#44]
```yaml
services:
  webserver:
    image: ${BEACH_WEBSERVER_IMAGE:-flownative/nginx}:${BEACH_WEBSERVER_IMAGE_VERSION:-3}
```

should default to 4. For this we need to teach the tool to update existing projects…
